import Head from 'next/head'
import Link from 'next/link'
import format from "date-fns/format"

import styles from '../styles/Home.module.css'

import { getPosts } from '../lib/posts';

import Layout from '../components/Layout';

export async function getStaticProps() {
  const posts = getPosts();

  return {
    props: {
      posts,
    }
  };
}

export default function Home({ posts }) {
  return (
    <Layout>
      <Head>
        <title>Site do Jean Lucas de Carvalho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {
            posts.map(({ title, slug, date }) => (
              <li key={slug} style={{ marginBottom: "20px" }}>
                <Link href={`/blog/${slug}`}>
                  <a>
                    <div>
                      {format(new Date(date), 'dd/MM/yyyy')}
                    </div>
                    <div>
                      {title}
                    </div>
                  </a>
                </Link>
              </li>
            ))
          }
        </ul>
      </main>
    </Layout>
  )
}
